version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=postgres://postgres:password@db:5432/scheduling?sslmode=disable
      - JWT_SECRET=your_jwt_secret
      - APP_ENV=development

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scheduling
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:latest
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:password@db:5432/scheduling?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

volumes:
  postgres_data:


